Repository undefined-ims-india/mkdev, pull requests merged in 2024-06, with the labels that each got.

#9 SETUP / User router
  server/routes/index.ts
  server/routes/routers/posts.ts
  server/routes/routers/users.ts
Labels: READY

#10 setup / server import syntax
  client/src/index.html
  server/index.ts
  server/routes/index.ts
  server/routes/messages.ts
Labels: READY

#15 SETUP / Tailwind setup
  client/src/components/App.tsx
  client/src/styling/index.css
  package-lock.json
  package.json
  postcss.config.ts
  prisma/schema.prisma
  tailwind.config.js
  webpack.config.js
Labels: READY

#13 feat / direct messages basic backend routes
  prisma/migrations/20240604172133_add_unique_user_username/migration.sql
  prisma/schema.prisma
  server/index.ts
  server/routes/conversations.ts
  server/routes/index.ts
  server/routes/messages.ts
Labels: READY

#14 FEAT / post-creation request handling
  prisma/migrations/20240604165742_user_defaults_edit/migration.sql
  prisma/schema.prisma
  server/routes/routers/posts.ts
  server/routes/routers/users.ts
Labels: READY

#12 Readme/ Contributing
  CONTRIBUTING.md
  README.md
Labels: documentation

#11 Auth
  client/src/components/App.tsx
  client/src/components/Login.tsx
  client/src/components/Logout.tsx
  client/src/index.tsx
  package-lock.json
  package.json
  server/auth.ts
  server/index.ts
  server/routes/index.ts
  server/routes/routers/auth.ts
  server/routes/routers/posts.ts
  server/routes/routers/users.ts
Labels: READY

#18 feat / messages socket setup and basic components
  client/src/components/App.tsx
  client/src/components/messages/Conversation.tsx
  client/src/components/messages/ConversationList.tsx
  client/src/components/messages/ConversationView.tsx
  client/src/components/messages/Conversations.tsx
  client/src/components/messages/Message.tsx
  client/src/components/messages/MessageInput.tsx
  client/src/components/messages/Messages.tsx
  client/src/components/messages/MessagesList.tsx
  client/src/components/messages/MessagesView.tsx
  client/src/index.html
  client/src/index.tsx
  package-lock.json
  package.json
  server/index.ts
Labels: READY

#16 Feat / Profile with auth fixes
  .gitignore
  client/src/components/App.tsx
  client/src/components/Login.tsx
  client/src/components/Nav.tsx
  client/src/components/Profile.tsx
  client/src/components/UserPosts.tsx
  client/src/index.tsx
  package.json
  prisma/migrations/20240607034716_profile_info/migration.sql
  prisma/schema.prisma
  server/index.ts
  server/routes/index.ts
  server/routes/routers/auth.ts
  server/routes/routers/posts.ts
  server/routes/routers/users.ts
Labels: READY

#17 FEAT / post creation post creation page
  client/src/components/MarkDown.tsx
  client/src/components/PostCreationPage.tsx
  package-lock.json
  package.json
Labels: READY

#23 FEAT / posts Image support
  .env.example
  client/src/components/PostCreationPage.tsx
  package-lock.json
  package.json
  prisma/schema.prisma
  server/helpers/aws-s3-upload.ts
  server/index.ts
  server/routes/routers/posts.ts
Labels: READY

#22 Readme
  .gitignore
  README.md
  prisma/seed.ts
  server/index.ts
  server/routes/routers/posts.ts
Labels: documentation

#21 messages / messaging components
  client/src/components/messages/Conversation.tsx
  client/src/components/messages/ConversationList.tsx
  client/src/components/messages/ConversationView.tsx
  client/src/components/messages/Conversations.tsx
  client/src/components/messages/Message.tsx
  client/src/components/messages/MessageInput.tsx
  client/src/components/messages/Messages.tsx
  client/src/components/messages/MessagesList.tsx
  client/src/components/messages/MessagesView.tsx
  server/index.ts
  server/routes/conversations.ts
  server/routes/messages.ts
Labels: READY

#24 FEAT / Profile page & login through Google
  client/src/components/App.tsx
  client/src/components/Dashboard.tsx
  client/src/components/Login.tsx
  client/src/components/Nav.tsx
  client/src/components/Profile.tsx
  client/src/components/UserPosts.tsx
  client/src/components/UsersPost.tsx
  package-lock.json
  package.json
  prisma/migrations/20240608205300_aws/migration.sql
  prisma/migrations/20240609201709_passport_user_google_id/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  server/auth.ts
  server/index.ts
  server/routes/routers/posts.ts
  server/routes/routers/users.ts
Labels: READY

#26 FIX / user-auth replaced Auth0 with Passport
  client/src/components/Login.tsx
  client/src/components/Profile.tsx
  client/src/components/UserPosts.tsx
  client/src/components/UsersPost.tsx
  package-lock.json
  package.json
  prisma/migrations/20240609032606_google_id_passport/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  server/index.ts
  server/routes/routers/posts.ts
Labels: READY

#29 FIX Merge errors
  client/src/components/Profile.tsx
  client/src/components/UserPosts.tsx
  server/index.ts
Labels: READY

#32 FIX / post creation - refactor to use logged in user, async function and custom submission handling
  .gitignore
  client/src/components/PostCreationPage.tsx
  server/helpers/aws-s3-upload.ts
  server/routes/routers/posts.ts
Labels: READY

#31 FEAT / Profile rendering logged in user /w blog components
  client/src/components/BlogItem.tsx
  client/src/components/Blogs.tsx
  client/src/components/Dashboard.tsx
  client/src/components/Profile.tsx
  client/src/components/UserPosts.tsx
  client/src/components/UsersPost.tsx
  package-lock.json
  package.json
  prisma/migrations/20240603152616_init/migration.sql
  prisma/migrations/20240604165742_user_defaults_edit/migration.sql
  prisma/migrations/20240604172133_add_unique_user_username/migration.sql
  prisma/migrations/20240607034716_profile_info/migration.sql
  prisma/migrations/20240608201802_tag_type_enum/migration.sql
  prisma/migrations/20240608205300_aws/migration.sql
  prisma/migrations/20240609032606_google_id_passport/migration.sql
  prisma/migrations/20240609164726_after/migration.sql
  prisma/migrations/20240609173145_fix/migration.sql
  prisma/migrations/20240609184304_revert_to_working/migration.sql
  prisma/migrations/20240609201709_passport_user_google_id/migration.sql
  prisma/migrations/20240610201235_/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  server/index.ts
  server/routes/index.ts
  server/routes/routers/blogs.ts
  server/routes/routers/posts.ts
  server/routes/routers/users.ts
Labels: READY

#33 FEAT/ repo showcases
  client/src/components/PostCreationPage.tsx
  client/src/components/post creation/Repo.tsx
  package-lock.json
  package.json
  prisma/migrations/20240610201235_/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  server/helpers/aws-s3-upload.ts
  server/routes/index.ts
  server/routes/routers/posts.ts
  server/routes/routers/repos.ts
Labels: READY

#34 Feat / Tab to display user's Posts and blogs
  .env.example
  client/src/components/BlogItem.tsx
  client/src/components/Blogs.tsx
  client/src/components/Dashboard.tsx
  client/src/components/Login.tsx
  client/src/components/Profile.tsx
  client/src/components/UserPosts.tsx
  client/src/components/UsersPost.tsx
  prisma/schema.prisma
  server/auth.ts
  server/routes/index.ts
  server/routes/routers/blogs.ts
  server/routes/routers/users.ts
Labels: READY

#36 Server tags fix
  prisma/schema.prisma
  prisma/seed.ts
  server/routes/routers/search.ts
Labels: READY

#37 messages / conversations with many users
  client/src/components/messages/Conversation.tsx
  client/src/components/messages/ConversationList.tsx
  client/src/components/messages/ConversationView.tsx
  client/src/components/messages/Message.tsx
  client/src/components/messages/MessageInput.tsx
  client/src/components/messages/Messages.tsx
  client/src/components/messages/MessagesList.tsx
  prisma/schema.prisma
  server/routes/conversations.ts
Labels: READY

#38 FEAT / User profiles basic implementation of profile
  client/src/components/Post.tsx
  client/src/components/UserProfile.tsx
  client/src/index.tsx
  prisma/schema.prisma
  server/routes/routers/users.ts
  types.ts
Labels: READY

#39 FIX / repos nested file creation
  README.md
  prisma/schema.prisma
  server/routes/routers/posts.ts
Labels: READY

#42 FIX / User profiles
  client/src/components/App.tsx
  client/src/components/Dashboard.tsx
  client/src/components/Nav.tsx
  client/src/components/Profile.tsx
  client/src/components/UserContext.tsx
  client/src/components/UserProfile.tsx
  client/src/index.tsx
  server/routes/routers/users.ts
  types.ts
Labels: READY

#44 FEAT / Feed
  client/src/components/Dashboard.tsx
  client/src/components/UserProfile.tsx
  client/src/components/UsersPost.tsx
  package-lock.json
  package.json
  prisma/schema.prisma
  server/index.ts
  server/routes/index.ts
  server/routes/routers/feed.ts
Labels: READY

#43 Added Sidebar to Dashboard
  client/src/components/App.tsx
  client/src/components/Dashboard.tsx
  client/src/components/Drawers.tsx
  client/src/components/Sidebar.tsx
  client/src/components/Tags.tsx
  prisma/seed.ts
  server/routes/index.ts
  server/routes/routers/tags.ts
Labels: READY

#41 Feat / User following setup
  client/src/components/Blogs.tsx
  client/src/components/Follow.tsx
  client/src/components/Followers.tsx
  client/src/components/Following.tsx
  client/src/components/Post.tsx
  client/src/components/UserPosts.tsx
  client/src/components/UserProfile.tsx
  client/src/components/UsersPost.tsx
  prisma/schema.prisma
  prisma/seed.ts
  server/routes/index.ts
  server/routes/routers/follows.ts
  server/routes/routers/posts.ts
  server/routes/routers/search.ts
  server/routes/routers/users.ts
  types.ts
Labels: READY

#47 Added Signup Survey
  client/src/components/Survey.tsx
  server/routes/routers/tags.ts
Labels: READY

#48 FIX / Post creation and dashboard styling
  client/src/components/App.tsx
  client/src/components/Post.tsx
  client/src/components/PostCreationPage.tsx
  client/src/components/post creation/Repo.tsx
Labels: READY

#45 feat / a11y change theme mvp
  client/src/components/App.tsx
  client/src/components/Nav.tsx
  client/src/components/messages/MessageInput.tsx
  client/src/index.tsx
  client/src/styling/ThemeToggle.tsx
  prisma/seed.ts
  server/routes/messages.ts
  server/routes/routers/users.ts
Labels: READY

#59 FIX / tag routes crashing server when NOT logged in.
  server/routes/routers/tags.ts
Labels: READY

#51 Feat / Follow & unfollow users
  client/src/components/Blogs.tsx
  client/src/components/Follow.tsx
  client/src/components/Followers.tsx
  client/src/components/Following.tsx
  client/src/components/UserPosts.tsx
  client/src/components/UserProfile.tsx
  client/src/components/UsersPost.tsx
  server/routes/routers/follows.ts
  server/routes/routers/tags.ts
Labels: READY

#55 FEAT / Post singe post view with repo file
  client/src/components/App.tsx
  client/src/components/FullPost.tsx
  client/src/components/Post.tsx
  client/src/components/RepoDisplay.tsx
  prisma/schema.prisma
  server/routes/routers/posts.ts
  server/routes/routers/users.ts
  types.ts
Labels: READY

#57 Added Dockerfile
  .dockerignore
  Dockerfile
  package.json
  server/index.ts
  tsconfig.json
  webpack.config.js
Labels: READY

#60 FIX / Corrected line that was removed when resolving conflicts in tags.ts
  server/routes/routers/tags.ts
Labels: READY

#56 Userinfo can be updated with github, linkedin, username, and dev.to id.
  .vscode/settings.json
  client/src/components/Follow.tsx
  client/src/components/UserContext.tsx
  client/src/components/UserInfo.tsx
  client/src/components/UserProfile.tsx
  server/index.ts
  server/routes/routers/follows.ts
Labels: READY

#62 FIX npm dev script and Dockerfile to access doubly nested server dist
  Dockerfile
  package.json
  server/index.ts
Labels: READY

#65 FIX Nav bar styling
  client/src/components/Nav.tsx
  client/src/styling/ThemeToggle.tsx
  server/routes/routers/users.ts
Labels: READY

#63 fix / websocket docker port
  Dockerfile
  server/index.ts
Labels: READY

#61 feat / messages add buttons
  client/src/components/messages/Conversation.tsx
  client/src/components/messages/ConversationList.tsx
  client/src/components/messages/ConversationView.tsx
  client/src/components/messages/Message.tsx
  client/src/components/messages/MessageInput.tsx
  client/src/components/messages/Messages.tsx
  client/src/components/messages/MessagesList.tsx
  prisma/schema.prisma
  server/routes/conversations.ts
  server/routes/messages.ts
Labels: READY

#66 FIX / Feed custom feed based on users follows
  server/routes/routers/feed.ts
  types.ts
Labels: READY

#64 FIX / follower-following button and info + following/follower styling
  .vscode/settings.json
  client/src/components/Follow.tsx
  client/src/components/Followers.tsx
  client/src/components/Following.tsx
  client/src/components/Nav.tsx
  client/src/components/UserProfile.tsx
  server/routes/routers/follows.ts
Labels: Changes Requested

#67 styling / add custom themes
  client/src/components/App.tsx
  client/src/components/Nav.tsx
  client/src/components/ThemeToggle.tsx
  client/src/components/messages/Conversation.tsx
  client/src/components/messages/Messages.tsx
  client/src/styling/themes.ts
Labels: READY

#69 FIX build error with RepoDisplay prop
  client/src/components/FullPost.tsx
  server/routes/routers/users.ts
Labels: READY

#70 FIX / Logout terminates user session and displays login screen
  client/src/components/Blogs.tsx
  client/src/components/Login.tsx
  client/src/components/Logout.tsx
  prisma/schema.prisma
  server/index.ts
Labels: READY

#71 FEAT / Post creation tags addition
  client/src/components/FullPost.tsx
  client/src/components/Post.tsx
  client/src/components/PostCreationPage.tsx
  client/src/components/Search.tsx
  client/src/components/Survey.tsx
  client/src/components/Tags.tsx
  client/src/components/post creation/Repo.tsx
  server/db/index.ts
  server/routes/routers/posts.ts
  server/routes/routers/search.ts
  server/routes/routers/tags.ts
  server/routes/routers/users.ts
Labels: READY

#76 added Seed script
  client/src/components/App.tsx
  prisma/seed.ts
Labels: READY

#78 FEAT / Likes persistance implemented
  client/src/components/Dashboard.tsx
  client/src/components/FullPost.tsx
  client/src/components/MarkDown.tsx
  client/src/components/Post.tsx
  client/src/components/UserContext.tsx
  client/src/components/UserProfile.tsx
  server/routes/routers/feed.ts
  server/routes/routers/posts.ts
  server/routes/routers/users.ts
  types.ts
Labels: READY

#75 FIX / Follower & following count & profile styles
  client/src/components/Follow.tsx
  client/src/components/Followers.tsx
  client/src/components/Following.tsx
  client/src/components/UserInfo.tsx
  client/src/components/UserProfile.tsx
  package-lock.json
  package.json
  prisma/schema.prisma
  server/routes/routers/follows.ts
  types.ts
Labels: READY

#77 UPDATE / Added Medium blogs to blogs list - removed blog description from view
  client/src/components/Blogs.tsx
  client/src/components/Followers.tsx
  client/src/components/Following.tsx
  client/src/components/UserInfo.tsx
  client/src/components/UserProfile.tsx
  prisma/schema.prisma
Labels: READY

#74 Greeting page
  client/src/components/App.tsx
  client/src/components/Login.tsx
  client/src/components/UserInfo.tsx
  client/src/components/Welcome.tsx
  client/src/index.html
Labels: READY

#79 FIX / Full post styling
  client/src/components/FullPost.tsx
  client/src/components/MarkDown.tsx
  client/src/styling/index.css
Labels: READY

#83 ADD glass-card style and background
  client/src/components/App.tsx
  client/src/components/Welcome.tsx
  client/src/styling/index.css
Labels: READY

#84 env / add callback url env variable
  .env.example
  server/index.ts
Labels: READY
